language: c
matrix:
  include:
    - os: linux
      dist: precise
      compiler:
        - clang
        - gcc
    - os: osx
      osx_image: xcode8.2
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get -y install gperf; fi
script: git submodule init && git submodule update && make && make install

