language: c
matrix:
  include:
    - os: linux
      dist: precise
    - os: osx
      osx_image: xcode8.2
addons:
  apt:
    packages:
      - gperf
script: git submodule init && git submodule update && make && make install
compiler:
  - clang
  - gcc
